### ISSUE TITLE
Ventilation

### ISSUE THREAD

**Issue by challo2018** [eloka080677/loxberry_vitoconnect#2]
Hi, wir hatten bereits im Loxforum kontakt. Ich würde gerne einige Funktionen zur Lüftung verwenden und habe diese bereits bei mir getestet. Wäre super wenn wir diese direkt in dein Plugin integrieren könnten. Soll ich dir die Änderungen schicken oder kannst du mich als Contributor hinzufügen dann kann ich mit den Änderungen ein Pull request stellen.
Gruß Fabian

**Comment by eloka080677** [comment]
Hab dich mit aufgenommen
